### ISSUE TITLE
error with npm  install 

### ISSUE THREAD

**Issue by sanekmihailow** [MrRio/vtop#127]
<d>
  <details>
    <summary>error</summary>

```javascript
2162 verbose lifecycle husky@0.14.3~install: PATH: /usr/share/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/vtop/node_modules/husky/node_modules/.bin:/usr/local/lib/node_modules/vtop/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
2163 verbose lifecycle husky@0.14.3~install: CWD: /usr/local/lib/node_modules/vtop/node_modules/husky
2164 silly lifecycle husky@0.14.3~install: Args: [ '-c', 'node ./bin/install.js' ]
2165 info lifecycle husky@0.14.3~install: Failed to exec install script
2166 verbose unlock done using /home/administrator/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
2167 silly rollbackFailedOptional Starting
2168 silly rollbackFailedOptional Finishing
2169 silly runTopLevelLifecycles Starting
2170 silly runTopLevelLifecycles Finishing
2171 silly install printInstalled
2172 verbose stack Error: husky@0.14.3 install: `node ./bin/install.js`
2172 verbose stack spawn ENOENT
2172 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
2172 verbose stack     at emitTwo (events.js:87:13)
2172 verbose stack     at ChildProcess.emit (events.js:172:7)
2172 verbose stack     at maybeClose (internal/child_process.js:821:16)
2172 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2173 verbose pkgid husky@0.14.3
2174 verbose cwd /home/administrator
2175 error Linux 4.4.0-128-generic
2176 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "vtop"
2177 error node v4.2.6
2178 error npm  v3.5.2
2179 error file sh
2180 error code ELIFECYCLE
2181 error errno ENOENT
2182 error syscall spawn
2183 error husky@0.14.3 install: `node ./bin/install.js`
2183 error spawn ENOENT
2184 error Failed at the husky@0.14.3 install script 'node ./bin/install.js'.
2184 error Make sure you have the latest version of node.js and npm installed.
2184 error If you do, this is most likely a problem with the husky package,
2184 error not with npm itself.
2184 error Tell the author that this fails on your system:
2184 error     node ./bin/install.js
2184 error You can get information on how to open an issue for this project with:
2184 error     npm bugs husky
2184 error Or if that isn't available, you can get their info via:
2184 error     npm owner ls husky
2184 error There is likely additional logging output above.
2185 verbose exit [ 1, true ]
```

</details>
</>

**Comment by sanekmihailow** [comment]
solution for Ubuntu 16
create symlink on nodejs
```
ln -s /usr/bin/nodejs  /usr/bin/node
```
and install n node manager version
```
/usr/bin/npm install -g n
node -v
n stable
npm install -g vtop
```
