### ISSUE TITLE
Crash on OS X 10.11

### ISSUE THREAD

**Issue by alrek-consulting** [MrRio/vtop#66]
Hi.

I don't know if I'm doing it wrong or what. But it appears that vtop is crashing when I move my cursor insiden the Terminal window.
I have uploaded a [video](https://www.youtube.com/watch?v=cYuxP0CQSvc&feature=youtu.be) on YouTube showing the problem.

This is on OS X 10.11.3

**Comment by mitogh** [comment]
I experienced the same issue as well.

With the following message after: 

> (node:23885) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

**Comment by PhilippMeissner** [comment]
I experience the same issue. My current workaround: Open `vtop` in a tmux-window.
Using Ubuntu 14.04.4 LTS, 64bit, Gnome Terminal 3.6.2 with zsh + oh-my-zsh installed.

**Comment by alexalv** [comment]
I experience the same issue. With almoust the same message as @mitogh 

> (node:20700) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version

Also, sometimes, (I was not able to evaluate what causes it exactly), I get the following trace

> TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at exports.spawn (child_process.js:383:9)
    at sudo (/usr/lib/node_modules/vtop/node_modules/sudo/lib/sudo.js:30:17)
    at Object.upgrade.install (/usr/lib/node_modules/vtop/upgrade.js:58:16)
    at Screen.<anonymous> (/usr/lib/node_modules/vtop/app.js:489:14)
    at Screen.EventEmitter._emit (/usr/lib/node_modules/vtop/node_modules/blessed/lib/events.js:86:20)
    at Screen.EventEmitter.emit (/usr/lib/node_modules/vtop/node_modules/blessed/lib/events.js:103:17)
    at Program.<anonymous> (/usr/lib/node_modules/vtop/node_modules/blessed/lib/widget.js:568:12)
    at emitTwo (events.js:106:13)

with no additional messages about graceful-fs.
Using archlinux, 64 bit, LilyTerm 0.9.9 with zsh + oh-my-zsh installed.

**Comment by rdebath** [comment]
I expect this is also https://github.com/MrRio/vtop/issues/40#issuecomment-226982911

Does it bomb out when the cursor is at about column 252 ?

**Comment by dubstrike** [comment]
Same issue. Here's some output that flashes in the terminal:

```
(node:15096) Warning: Possible EventEmitter memory leak d       . 11 exit listeners a   d. U e emit   .setMaxListeners() to increase limit
(node:15096) Warning: Possible EventEmitter memory leak d         11 keypress listene   adde . Use    tter.setMaxListeners() to increase limit
(node:15096) Warning: Possible EventEmitter memory leak d       . 11 resize listeners   ded. Use em   er.setMaxListeners() to increase limit
(node:15096) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
npm

WARN
 deprecated
 graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm
WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

/Users/Wojtek/.node/bin/vtop -> /Users/Wojtek/.node/lib/node_modules/vtop/bin/vtop.js

/Users/Wojtek/.node/lib
└── vtop@0.5.5


Finished updating. Clearing cache and relaunching...
(node:15096) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:15096) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by specious** [comment]
Seems like it's fixed in 0.5.7 👍
