### ISSUE TITLE
"Not a terminal" on Windows with MinTTY

### ISSUE THREAD

**Issue by mateon1** [MrRio/vtop#67]
On Windows, while using the MinTTY executable packaged with MSYS2, vtop crashes saying "Not a terminal".
I'm unable to use the default Windows commandline, as it doesn't support the unicode characters needed for graph display.
Here's the full stack info if needed:
```
C:\Users\matin\AppData\Roaming\npm\node_modules\vtop\node_modules\blessed\lib\program.js:241
    throw new Error('Not a terminal.');
    ^

Error: Not a terminal.
    at Program.listen (C:\Users\matin\AppData\Roaming\npm\node_modules\vtop\node_modules\blessed\lib\program.js:241:11)
    at new Program (C:\Users\matin\AppData\Roaming\npm\node_modules\vtop\node_modules\blessed\lib\program.js:89:8)
    at Function.Program (C:\Users\matin\AppData\Roaming\npm\node_modules\vtop\node_modules\blessed\lib\program.js:28:12)
    at C:\Users\matin\AppData\Roaming\npm\node_modules\vtop\app.js:18:21
    at Object.<anonymous> (C:\Users\matin\AppData\Roaming\npm\node_modules\vtop\app.js:646:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by illinoisjackson** [comment]
I got this issue as well, in fact I found similar compatibility issues with other libraries/programs such as blessed when using MinTTY.
